refactor: simplify test, improvements on code

diff --git a/.github/workflows/manual-release.yml b/.github/workflows/manual-release.yml
--- a/.github/workflows/manual-release.yml
+++ b/.github/workflows/manual-release.yml
@@ -63,8 +63,43 @@ jobs:
           git config --global user.email "${USER_EMAIL}"
 
       - name: Execute Release Process
-        run: make release-${{ github.event.inputs.version_bump }}
-        
+        run: |
+          if [[ "${{ github.event.inputs.version_bump }}" == "major" ]]; then
+            make release-major
+          elif [[ "${{ github.event.inputs.version_bump }}" == "minor" ]]; then
+            make release-minor
+          elif [[ "${{ github.event.inputs.version_bump }}" == "patch" ]]; then
+            make release-patch
+          else
+            echo "Invalid version_bump input"
+            exit 1
+          fi
+
+      - name: Build Project
+        if: ${{ github.event.inputs.build_and_upload == 'true' }}
+        run: make build
+
+      - name: Configure AWS credentials
+        if: ${{ github.event.inputs.build_and_upload == 'true' }}
+        uses: aws-actions/configure-aws-credentials@v4
+        with:
+          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          aws-region: ${{ vars.AWS_REGION }}
+
+      - name: Upload to S3
+        if: ${{ github.event.inputs.build_and_upload == 'true' }}
+        run: |
+          echo "Uploading wheel files to S3 bucket"
+          aws s3 cp dist/python_base_project-latest.whl s3://${{ vars.S3_BUCKET_NAME }}/
+          VERSION=$(uv version | grep -oE '[0-9]+\.[0-9]+\.[0-9]+')
+          if [[ "${{ github.event.inputs.version_bump }}" =~ ^(major|minor|patch)$ ]]; then
+            make release-${{ github.event.inputs.version_bump }}
+          else
+            echo "Invalid version_bump input"
+            exit 1
+          fi
+
       - name: Build Project
         if: ${{ github.event.inputs.build_and_upload == true }}
         run: make build
